<?php 
include ('header.php');
echo '<table width="100%" style="border: 1px solid black">';
echo '<tr>';
	echo '<td colspan="3" style="padding: 3px; background-color: black; color: white">Scouts</td>';
echo '</tr>';
// Keepers
	echo '<tr>';
		echo '<td colspan="3" bgcolor="#999999"><strong>Keepers</strong></td>';
	echo '</tr>';
	echo '<tr bgcolor="#CCCCCC">';
		echo '<td>Ronde/Rol</td>';
		echo '<td>Manager</td>';
		echo '<td>Team-id</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Hoofd</td>';
		echo '<td style="border-top: 1px solid black">Trainer-M</td>';
		echo '<td style="border-top: 1px solid black">1294192</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 16</td>';
		echo '<td style="border-top: 1px solid black">DrRock</td>';
		echo '<td style="border-top: 1px solid black">148809</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Kwalificatie WK 16</td>';
		echo '<td style="border-top: 1px solid black">DrRock</td>';
		echo '<td style="border-top: 1px solid black">148809</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 15</td>';
		echo '<td style="border-top: 1px solid black">DrRock</td>';
		echo '<td style="border-top: 1px solid black">148809</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Kwalificatie WK 15</td>';
		echo '<td style="border-top: 1px solid black">DrRock</td>';
		echo '<td style="border-top: 1px solid black">148809</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 14</td>';
		echo '<td style="border-top: 1px solid black">8noortje8</td>';
		echo '<td style="border-top: 1px solid black">811636</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">20+</td>';
		echo '<td style="border-top: 1px solid black">DrRock</td>';
		echo '<td style="border-top: 1px solid black">148809</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td colspan="3"></td>';
	echo '</tr>';
// Verdedigers
	echo '<tr>';
		echo '<td colspan="3" bgcolor="#999999"><strong>Verdedigers</strong></td>';
	echo '</tr>';
	echo '<tr bgcolor="#CCCCCC">';
		echo '<td>Ronde/Rol</td>';
		echo '<td>Manager</td>';
		echo '<td>Team-id</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Hoofd</td>';
		echo '<td style="border-top: 1px solid black">Ace21</td>';
		echo '<td style="border-top: 1px solid black">360202</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 16</td>';
		echo '<td style="border-top: 1px solid black">remkovandegraaf</td>';
		echo '<td style="border-top: 1px solid black">208116</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Kwalificatie WK 16</td>';
		echo '<td style="border-top: 1px solid black">remkovandegraaf</td>';
		echo '<td style="border-top: 1px solid black">208116</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 15</td>';
		echo '<td style="border-top: 1px solid black">Ace21</td>';
		echo '<td style="border-top: 1px solid black">360202</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Kwalificatie WK 15</td>';
		echo '<td style="border-top: 1px solid black">Ace21</td>';
		echo '<td style="border-top: 1px solid black">360202</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 14</td>';
		echo '<td style="border-top: 1px solid black">ROLADE</td>';
		echo '<td style="border-top: 1px solid black">505323</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">20+</td>';
		echo '<td style="border-top: 1px solid black">_EriQ_</td>';
		echo '<td style="border-top: 1px solid black">363868</td>';  
	echo '</tr>';
// Middenvelders
	echo '<tr>';
		echo '<td colspan="3"></td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td colspan="3" bgcolor="#999999"><strong>Middenvelders</strong></td>';
	echo '</tr>';
	echo '<tr bgcolor="#CCCCCC">';
		echo '<td>Ronde/Rol</td>';
		echo '<td>Manager</td>';
		echo '<td>Team-id</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Hoofd</td>';
		echo '<td style="border-top: 1px solid black">RoyGroteboer</td>';
		echo '<td style="border-top: 1px solid black">765137</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 16</td>';
		echo '<td style="border-top: 1px solid black">RoyGroteboer</td>';
		echo '<td style="border-top: 1px solid black">765137</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Kwalificatie WK 16</td>';
		echo '<td style="border-top: 1px solid black">RoyGroteboer</td>';
		echo '<td style="border-top: 1px solid black">765137</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 15</td>';
		echo '<td style="border-top: 1px solid black">Dennis77</td>';
		echo '<td style="border-top: 1px solid black">1008816</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Kwalificatie WK 15</td>';
		echo '<td style="border-top: 1px solid black">Dennis77</td>';
		echo '<td style="border-top: 1px solid black">1008816</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 14</td>';
		echo '<td style="border-top: 1px solid black">RoyGroteboer</td>';
		echo '<td style="border-top: 1px solid black">765137</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">20+</td>';
		echo '<td style="border-top: 1px solid black">Arnando</td>';
		echo '<td style="border-top: 1px solid black">1363746</td>';  
	echo '</tr>';
// Vleugelspelers
	echo '<tr>';
		echo '<td colspan="3"></td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td colspan="3" bgcolor="#999999"><strong>Vleugelspelers</strong></td>';
	echo '</tr>';
	echo '<tr bgcolor="#CCCCCC">';
		echo '<td>Ronde/Rol</td>';
		echo '<td>Manager</td>';
		echo '<td>Team-id</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Hoofd</td>';
		echo '<td style="border-top: 1px solid black">Diede</td>';
		echo '<td style="border-top: 1px solid black">210619</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 16</td>';
		echo '<td style="border-top: 1px solid black">DJ-Dijkie</td>';
		echo '<td style="border-top: 1px solid black">212474</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Kwalificatie WK 16</td>';
		echo '<td style="border-top: 1px solid black">DJ-Dijkie</td>';
		echo '<td style="border-top: 1px solid black">212474</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 15</td>';
		echo '<td style="border-top: 1px solid black">gigantic123</td>';
		echo '<td style="border-top: 1px solid black">207270</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Kwalificatie WK 15</td>';
		echo '<td style="border-top: 1px solid black">gigantic123</td>';
		echo '<td style="border-top: 1px solid black">207270</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 14</td>';
		echo '<td style="border-top: 1px solid black">Diede</td>';
		echo '<td style="border-top: 1px solid black">210619</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">20+</td>';
		echo '<td style="border-top: 1px solid black">Koning-Goedhart</td>';
		echo '<td style="border-top: 1px solid black">506079</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td colspan="3"></td>';
	echo '</tr>';
// Spitsen
	echo '<tr>';
		echo '<td colspan="3" bgcolor="#999999"><strong>Spitsen</strong></td>';
	echo '</tr>';
	echo '<tr bgcolor="#CCCCCC">';
		echo '<td>Ronde/Rol</td>';
		echo '<td>Manager</td>';
		echo '<td>Team-id</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Hoofd</td>';
		echo '<td style="border-top: 1px solid black">masterful</td>';
		echo '<td style="border-top: 1px solid black">767671</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 16</td>';
		echo '<td style="border-top: 1px solid black">JJHoitema</td>';
		echo '<td style="border-top: 1px solid black">501781</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Kwalificatie WK 16</td>';
		echo '<td style="border-top: 1px solid black">JJHoitema</td>';
		echo '<td style="border-top: 1px solid black">501781</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 15</td>';
		echo '<td style="border-top: 1px solid black">robbert1982</td>';
		echo '<td style="border-top: 1px solid black">69164</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Kwalificatie WK 15</td>';
		echo '<td style="border-top: 1px solid black">robbert1982</td>';
		echo '<td style="border-top: 1px solid black">69164</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Eindronde WK 14</td>';
		echo '<td style="border-top: 1px solid black">HFR_schuimhoofd2</td>';
		echo '<td style="border-top: 1px solid black">150852</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">20+</td>';
		echo '<td style="border-top: 1px solid black">Mod-Koren</td>';
		echo '<td style="border-top: 1px solid black">503347</td>';  
	echo '</tr>';
// MS
	echo '<tr>';
		echo '<td colspan="3"></td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td colspan="3" bgcolor="#999999"><strong>Multiskillscouts</strong></td>';
	echo '</tr>';
	echo '<tr bgcolor="#CCCCCC">';
		echo '<td>Ronde/Rol</td>';
		echo '<td>Manager</td>';
		echo '<td>Team-id</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">U22-spelers</td>';
		echo '<td style="border-top: 1px solid black">masterful</td>';
		echo '<td style="border-top: 1px solid black">767671</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">22+-spelers</td>';
		echo '<td style="border-top: 1px solid black">kopsterkespits</a></td>';
		echo '<td style="border-top: 1px solid black">145644</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td colspan="3"></td>';
	echo '</tr>';
// XTC
	echo '<tr>';
		echo '<td colspan="3" bgcolor="#999999"><strong>Project XTC</strong></td>';
	echo '</tr>';
	echo '<tr bgcolor="#CCCCCC">';
		echo '<td>Ronde/Rol</td>';
		echo '<td>Manager</td>';
		echo '<td>Team-id</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Projectleider</td>';
		echo '<td style="border-top: 1px solid black">thunder</td>';
		echo '<td style="border-top: 1px solid black">767527</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Projectleider</td>';
		echo '<td style="border-top: 1px solid black">Pretty</td>';
		echo '<td style="border-top: 1px solid black">205783</td>';  
	echo '</tr>';
//U17
	echo '<tr>';
		echo '<td colspan="3"></td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td colspan="3" bgcolor="#999999"><strong>U17-scouting</strong></td>';
	echo '</tr>';
	echo '<tr bgcolor="#CCCCCC">';
		echo '<td>Ronde/Rol</td>';
		echo '<td>Manager</td>';
		echo '<td>Team-id</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Projectleider</td>';
		echo '<td style="border-top: 1px solid black">schaart</td>';
		echo '<td style="border-top: 1px solid black">212307</td>';  
	echo '</tr>';
//Hoofdscout
	echo '<tr>';
		echo '<td colspan="3"></td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td colspan="3" bgcolor="#999999"><strong>Scouting algemeen</strong></td>';
	echo '</tr>';  	
	echo '<tr bgcolor="#CCCCCC">';
		echo '<td>Ronde/Rol</td>';
		echo '<td>Manager</td>';
		echo '<td>Team-id</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">Hoofd scouting</td>';
		echo '<td style="border-top: 1px solid black">BC-asafe</td>';
		echo '<td style="border-top: 1px solid black">70060</td>';  
	echo '</tr>';
// Bondscoaches
	echo '<tr>';
		echo '<td colspan="3"></td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td colspan="3" bgcolor="#999999"><strong>Bondscoaches</strong></td>';
	echo '</tr>';  	
	echo '<tr bgcolor="#CCCCCC">';
		echo '<td>Ronde/Rol</td>';
		echo '<td>Manager</td>';
		echo '<td>Team-id</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">BC NT</td>';
		echo '<td style="border-top: 1px solid black">jestar</td>';
		echo '<td style="border-top: 1px solid black">513519</td>';  
	echo '</tr>';
	echo '<tr>';
		echo '<td style="border-top: 1px solid black">BC U20</td>';
		echo '<td style="border-top: 1px solid black">GM-Koers</td>';
		echo '<td style="border-top: 1px solid black">143926</td>';  
	echo '</tr>';
echo '</table>';
include ('footer.php');
?>